### ISSUE TITLE
bitnami_redmine_Xapian not available

### ISSUE THREAD

**Issue by twoyoungtwosimple** [xelkano/redmine_xapian#101]
Hi, I got "Xapian not available", I have no idea, when I already installed xapian and  xapian-full-alaveteli. Is it not that I have not completed the binding? How to bind?
Thanks!
bitnami_redmine_Xapian not available
_info:
Environment:
  Redmine version                4.0.2.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.11.1
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   2.0.0

#apt list --installed | grep xapi

libsearch-xapian-perl/xenial,now 1.2.21.0-1build2 amd64 [installed,upgradable to: 1.2.25.0-1.99xenial+1]
libxapian-dev/xenial,now 1.4.10-1.99xenial+1 amd64 [installed]
libxapian22v5/xenial,now 1.2.22-2 amd64 [installed]
libxapian30/xenial,now 1.4.10-1.99xenial+1 amd64 [installed,automatic]
python-xapian/xenial,now 1.4.10-1.99xenial+1 amd64 [installed]
ruby-xapian/xenial,now 1.4.10-1.99xenial+1 amd64 [installed]
xapian-omega/xenial,now 1.4.10-1.99xenial+1 amd64 [installed]

**Comment by picman** [comment]
It's not the pugin's problem but the Bitnami's problem. The plugin just requires Xapian binding available. I'm not and expert on Bitnami. It's out of scope of this plugin development to deal with such systems. Use Linux + web server + Redmine and make your life easier.
