### ISSUE TITLE
search inside file ( words or excel or ....)

### ISSUE THREAD

**Issue by ashrafalzyoud** [xelkano/redmine_xapian#104]
if there any way to full search inside files words or excel

**Comment by ashrafalzyoud** [comment]
![Untitled](https://user-images.githubusercontent.com/50211455/76305120-3a0d7680-62cd-11ea-9ac4-86f05a4b828b.png)
i need search (words) insdie files extention (word or excel ....)

**Comment by picman** [comment]
That's exactly the purpose of this plugin, to full-text search inside documents, including MS Word and Excel. What's the problem? Have you installed the plugin properly according to README?

**Comment by atopcu** [comment]
Hello picman,

I installed plugin in my redmine instance. Indexing is working. But search cannot found inside words of indexed documents.  
I am using redmine 3.4.13-stable and https://github.com/xelkano/redmine_xapian/tree/0cf1ddd7b4469534a0b7ff9e08c52d92d5328922

Note: I am using redmine_dmsf indexing extension too on different db folder on same redmine instance and it is working correctly for DMSF files.

BR

**Comment by picman** [comment]
1. Check the plugin's settings, whether you refer the right index file(database).
2. Don't forget to uncheck "Search in titles only" while searching.
3. Check production.log for any errors related to searching.

**Comment by atopcu** [comment]
Thanks picman. db folder on plugin settings was different than indexer file.
BR
