### ISSUE TITLE
Plugin xapian not appearing in redmine plugins list

### ISSUE THREAD

**Issue by zumodevidrio** [xelkano/redmine_xapian#105]
Redmine version: 4.1.1
Xapian plugin version: 2.0.1

Environment:
Redmine installed in a docker container. The redmine folder is a shared volume with the host VM. Xapian plugin installed by following the point 1.2 of the readme.md file.

After installing Xapian plugin on redmine it doesn't appear in the plugins list. All other plugins are properly listed. The permissions for the xapian plugin folder are the correct ones.

**Comment by picman** [comment]
Is it plugin physically located in  _plugins/redmine_xapian_ ?

**Comment by zumodevidrio** [comment]
Yes, it is

**Comment by picman** [comment]
That's strange. If _plugins/redmine_xapian_ exists and the folder has the same permissions as the other plugin's folders, it should appear in the plugin list.
Check log/production.log for any errors related to the plugin.

**Comment by zumodevidrio** [comment]
Yes, I can't figure out why it's not appearing this time. In production log the only appearence for xapian is:

> Starting Maintenance Mode plugin for Redmine
> Creating scope :sorted. Overwriting existing method Group.sorted.
> Creating scope :sorted. Overwriting existing method User.sorted.
> No Xapian search engine interface for Ruby installed => Full-text search won't be available.
>                       Install a ruby-xapian package or an alternative Xapian binding (https://xapian.org).
> Creating scope :visible. Overwriting existing method AgileQuery.visible.
> No Xapian search engine interface for Ruby installed => Full-text search won't be available.
>                       Install a ruby-xapian package or an alternative Xapian binding (https://xapian.org).
> cannot load such file -- xapian

**Comment by picman** [comment]
Follow the recommendation given in the production.log. Install ruby-xapian package. See the readme for more details.

**Comment by picman** [comment]
Check the discussion under this issue: https://github.com/danmunn/redmine_dmsf/issues/769

**Comment by zumodevidrio** [comment]
The funny thing is that the package is already installed:

`# apt-get install ruby-xapian
Reading package lists... Done
Building dependency tree
Reading state information... Done
ruby-xapian is already the newest version (1.4.11-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

Why is the log complaining about it?

**Comment by picman** [comment]
You need to have Xapian biindings installed in the docker container. See the issue.

**Comment by zumodevidrio** [comment]
Of course, in the container I have installed:

> /opt/redmine# dpkg -l | grep -i ruby
> ii  libruby2.5:amd64                   2.5.5-3+deb10u1              amd64        Libraries necessary to run Ruby 2.5
> ii  rake                               12.3.1-3+deb10u1             all          ruby make-like utility
> ii  ruby                               1:2.5.1                      amd64        Interpreter of object-oriented scripting language Ruby (default version)
> ii  ruby-did-you-mean                  1.2.1-1                      all          smart error messages for Ruby > 2.3
> ii  ruby-minitest                      5.11.3-1                     all          Ruby test tools supporting TDD, BDD, mocking, and benchmarking
> ii  ruby-net-telnet                    0.1.1-2                      all          telnet client library
> ii  ruby-power-assert                  1.1.1-1                      all          library showing values of variables and method calls in an expression
> ii  ruby-test-unit                     3.2.8-1                      all          unit testing framework for Ruby
> ii  ruby-xapian                        1.4.11-2                     amd64        Xapian search engine interface for Ruby
> ii  ruby-xmlrpc                        0.3.0-2                      all          XMLRPC library for Ruby
> ii  ruby2.5                            2.5.5-3+deb10u1              amd64        Interpreter of object-oriented scripting language Ruby
> ii  rubygems-integration               1.11+deb10u1                 all          integration of Debian Ruby packages with Rubygems

And:

> /opt/redmine# dpkg -l | grep -i xapian
> ii  libxapian-dev                      1.4.11-1                     amd64        Development files for Xapian search engine library
> ii  libxapian30:amd64                  1.4.11-1                     amd64        Search engine library
> ii  ruby-xapian                        1.4.11-2                     amd64        Xapian search engine interface for Ruby
> ii  xapian-omega                       1.4.11-1                     amd64        CGI search interface and indexers using Xapian

The package ruby-xapian includes xapian bindings, isn't it? Am I missing something?

**Comment by zumodevidrio** [comment]
I have deployed another container with redmine 4.0.7 and I find the same issue.

**Comment by picman** [comment]
I've no experience with the docker, but I'd try to install Xapian Bindings from source codes.

**Comment by Luckyvb** [comment]
I build Xapian Bindings where i must copy library?

**Comment by Luckyvb** [comment]
after build copy/symlink xapian.rb and _xapian.so to redmine/vendor folder.

**Comment by picman** [comment]
```
cd xapian-core-1.4.15
./configure
make
sudo make install
cd ../xapian-bindings-1.4.15  
./configure
make
sudo make install
cd ../xapian-omega-1.4.15
./configure
make
sudo make install
```
