### ISSUE TITLE
HTTP 403 error when saving settings in https-only web-server

### ISSUE THREAD

**Issue by jip** [xelkano/redmine_xapian#107]
My environment is: Debian 10.6 x86_64, Nginx 1.14.2, Puma 3.12.6, Redmine 4.1.1, redmine_xapian 2.0.2, xapian-core 1.4.17, xapian-omega 1.4.17, xapian-bindings 1.4.17. Nginx was configured to accept https only on port 443. With this setting an every try to save plugin configuration initiates a HTTP request:
```
POST https://redmine.domain.com/settings/plugin/redmine_xapian
```
which leads to HTTP 403 error. The reason was, redmine_xapian plugin's response includes a HTTP header:
```
Location: http://redmine.domain.com/settings/plugin/redmine_xapian
```
(note 'http://' not 'https://').
After nginx was configured to redirect all HTTP traffic to HTTPS, an error gone.

If this trouble is not on the plugin side, it maybe deserves to be mentioned in docs.

**Comment by picman** [comment]
All the links in the plugin are relative. Can't it be something wrong in your configuration? E.g. **Protocol** and path in the Redmine's **_Administration / Settings_**?

**Comment by jip** [comment]
Administration / Settings / General: Protocol == HTTPS.
Didn't found any path-related settings.
