### ISSUE TITLE
Bad repository link on search results 

### ISSUE THREAD

**Issue by aij00** [xelkano/redmine_xapian#109]
Search result link is bad, only repository, other link is good.
similar to #16
result point to -> https://myhost/projects/XXXX/repository/...
right link is  -> https://myhost/redmine/projects/XXXX/repository/...

result link loose /redmine/ location.

Can I set location in config?

**Comment by picman** [comment]
Could you test with the devel branch? The solution supposes the following variable set in your configuration.
```ruby
Redmine::Utils::relative_url_root = '/redmine'
```

**Comment by aij00** [comment]
Thank you.
I test dev branch, but not fix the problem.

my config, redmine/config/environment.rb has 
`Redmine::Utils::relative_url_root = '/redmine'`

**Comment by picman** [comment]
In _config/additional_environment.rb_ I have 
```ruby
# Sub-uri test
config.relative_url_root = '/redmine'
```
In the modified _plugins/redmine_xapian/app/models/repofile.rb_ I have
```ruby
def event_url
  File.join Redmine::Utils::relative_url_root, url    
end
```
If I restart the environment then and search inside repositories, I can see modified links pointing to _/redmine_ sub-uri
```
http://localhost:3000/redmine/projects/c1/repository/svn/entry/readme.txt
```

**Comment by aij00** [comment]
It's working as expected.

> In _config/additional_environment.rb_ I have
> 
> ```ruby
> # Sub-uri test
> config.relative_url_root = '/redmine'
> ```

I have lost above config, and set again, it's work.
Thank you for your quick fix and advise.
