### ISSUE TITLE
In search result, chinese description is garbled

### ISSUE THREAD

**Issue by keineahnung2345** [xelkano/redmine_xapian#111]
When I search the text "判断" in my document, it shows the following result:
![image](https://user-images.githubusercontent.com/18047300/125423078-e88781af-3f4c-4caf-ba6c-768aeb8e6885.png)

I've found that's because in the following lines:

https://github.com/xelkano/redmine_xapian/blob/fedf924a377dbb89b866f645428ee9aafe9207eb/lib/redmine_xapian/xapian_search.rb#L196-L198

`dochash[:sample].encoding` is ASCII-8BIT, which should be UTF-8 instead.
After I changed `dochash[:sample].encode('UTF-8', dochash[:sample].encoding, ...)` into `dochash[:sample].encode('UTF-8', 'UTF-8', ...)`, the search result becomes normal:

![image](https://user-images.githubusercontent.com/18047300/125424794-fe3a1c69-23cc-498a-8de6-963b9dabd1f6.png)

But it's just a workaround, and I don't know why `dochash[:sample]` is detected as ASCII-8BIT encoding. Is there a better fix? Thanks.

**Comment by keineahnung2345** [comment]
I've found that in:
https://github.com/xelkano/redmine_xapian/blob/fedf924a377dbb89b866f645428ee9aafe9207eb/lib/redmine_xapian/xapian_search.rb#L77-L79

`query_string` is UTF-8, but `query.description` is `ASCII-8BIT`, but I can't find related information in xapian's website.

**Comment by picman** [comment]
![image](https://user-images.githubusercontent.com/779003/131853332-798dffe2-2329-4a6d-95e8-eec329800595.png)
