### ISSUE TITLE
omindex directory

### ISSUE THREAD

**Issue by boki69** [xelkano/redmine_xapian#128]
Hi Karel,

I've tested this great plugin (devel-2.0.6) on my Redmine 5 migration.
It works, but there is a misunderstood i think.

On plugin configuration page, i can setup the database path:
![image](https://user-images.githubusercontent.com/3695756/164703884-3ddcd344-a5f1-45fa-b3bd-3521ce7e83e1.png)

But the **redmine/plugins/redmine_xapian/extra/xapian_indexer.rb** don't use it. It uses the default directory and index files.
This is hardcoded in the script.

Maybe it is better to use this configuration in the script too, if we start the script without **-t** switch.

Best Regards!

**Comment by picman** [comment]
The script has no access to the Redmine's database to get those plugin's option. So, it's hard coded in the script here:

```ruby
44 # Directory containing Xapian databases for omindex (Attachments indexing)
45 $dbrootpath = File.expand_path('file_index', $redmine_root)
```
If you don't use the default path, you can change it here. It's not much user friendly, but I don't know how to do that better.
