### ISSUE TITLE
JSON::ParserError (859: unexpected token at

### ISSUE THREAD

**Issue by keineahnung2345** [xelkano/redmine_xapian#141]
In devel branch, I have to revert the change in https://github.com/xelkano/redmine_xapian/commit/15e120845b0f3865b636cd3bdb17bf8ee4dd97d5
a.k.a: change `attributes = JSON.parse(value.gsub(/:([a-zA-z]+)/, '"\\1"').gsub('=>', ': ')).symbolize_keys` to `attributes = eval value`  to get rid of JSON::ParserError.

**Comment by picman** [comment]
`eval` is not acceptable. What is the error? Cannot be changed the REGEXP to fix the error?

**Comment by keineahnung2345** [comment]
The remaining part of the error message is just the json file. Maybe this error happens because my file is in Chinese.

**Comment by picman** [comment]
Post the file, I will try it.

**Comment by picman** [comment]
I have tried to index a file with some Chinese words and it worked fine:
![image](https://github.com/xelkano/redmine_xapian/assets/779003/09b157fc-74af-4be6-b64b-39bd56206c69)

**Comment by keineahnung2345** [comment]
Thank you. I've also found that it works for my other Chinese files. But that file is somehow credential, I'll check what's wrong myself.

**Comment by keineahnung2345** [comment]
After applying the PR above, there's still another problem for my Chinese docx file, `attributes[:filename]` should be `客戶.docx`, but it will be shown as `xE5xAExA2xE6x88xB6.docx`. It seems `JSON.parse` eats the backslashes. 
Also `attributes[:url]` is affected so the links shown are invalid.

**Comment by picman** [comment]
I believe, that I've fixed most of the reported problems:
1. Filenames are parsed correctly.
2. The URL is correct even from repositories without identifiers.
3. xapian-ruby gem added to the Gemfile

**Comment by keineahnung2345** [comment]
Yes, the `instance_eval` works like a charm.
