### ISSUE TITLE
Random Mysql::Error: 

### ISSUE THREAD

**Issue by KammutierSpule** [xelkano/redmine_xapian#19]
Some times, random messages apears while opening pages

Mysql::Error: Unknown column 'kb_articles.created_on' in 'where clause': SELECT `kb_articles`.`id` AS t0_r0, `kb_articles`.`category_id` AS t0_r1, `kb_articles`.`title` AS t0_r2, `kb_articles`.`summary` AS t0_r3, `kb_articles`.`content` AS t0_r4, `kb_articles`.`created_at` AS t0_r5, `kb_articles`.`updated_at` AS t0_r6, `kb_articles`.`author_id` AS t0_r7, `kb_articles`.`comments_count` AS t0_r8, `kb_articles`.`project_id` AS t0_r9, `projects`.`id` AS t1_r0, `projects`.`name` AS t1_r1, `projects`.`description` AS t1_r2, `projects`.`homepage` AS t1_r3, `projects`.`is_public` AS t1_r4, `projects`.`parent_id` AS t1_r5, `projects`.`created_on` AS t1_r6, `projects`.`updated_on` AS t1_r7, `projects`.`identifier` AS t1_r8, `projects`.`status` AS t1_r9, `projects`.`lft` AS t1_r10, `projects`.`rgt` AS t1_r11, `projects`.`dmsf_description` AS t1_r12 FROM `kb_articles` LEFT OUTER JOIN `projects` ON `projects`.id = `kb_articles`.project_id WHERE ((kb_articles.created_on <'2011-12-14 11:51:07')) AND ((((projects.status=1) AND (projects.is_public = 1 OR projects.id IN (32,63,8,7,27,61,31,29,28,30,10,18,36,35,17,9,22,11,34) OR projects.id IN (32,8,7,61,31,29,28,30,10,18,17,9,22,11)))) AND (((LOWER(kb_articles.title) LIKE '%pdf%') OR (LOWER(kb_articles.content) LIKE '%pdf%')))) ORDER BY kb_articles.id DESC LIMIT 11: database error, please configure xapian

what that should mean?
It starts appear after last Redmine svn updates...

**Comment by picman** [comment]
Fixed.
