### ISSUE TITLE
Cannot display extern files, found by xapian

### ISSUE THREAD

**Issue by mojovski** [xelkano/redmine_xapian#20]
Hi, I have a following use case:

* I have files (word, pdf, ...) stored unindexed in some folder
* I use omindex and xapian to index them
* When I search in Redmine for some query, I would like they to appear in the search result.

The files are not uploaded via redmine. I rather try to import an existing messy storage of data.

Obviously the found files, which are NOT beeing identified in Redmine as Attachments, are discarded.

Would it make sense to change this behaviour? Maybe writing a method XapianSearch.seach_externally(...) ?

Or maybe to to "import" all Files as Attachments? But how one could do this automatically?

Looking forward to hear from you!

Thanks alot!

**Comment by picman** [comment]
Non Redmine objects are not supported.
