### ISSUE TITLE
No results with plugin

### ISSUE THREAD

**Issue by boozer** [xelkano/redmine_xapian#40]
I installed your Plugin in Redmine 2.1.2. Searching in attachments works fine, but as soon as your plugin is installed searching for issues breaks down. For a example search over all projects I normally get 300+ results. Now I still get 300+ results, but it's only possible to view the first 13. Searching in a specific project or project and it's subprojects is even worse. Every search now returns 0 results, even searches wich normally return 100+.
This error is untolerable for I really need to be able to search in projects, but I also need search in attachments and I actually like your plugin very much.

Please help me.

**Comment by picman** [comment]
Fixed.
