### ISSUE TITLE
Search in "Project and its subprojects" fails

### ISSUE THREAD

**Issue by duboisst** [xelkano/redmine_xapian#48]
I have installed redmine_xapian plugin (v1.6.1) and it works fine except if the search scope is "Project and its subprojects"
In this case I get the following error message:
undefined method `id' for #: searching model "wiki_pages"

I get the same error for any searching model :
undefined method 'id' for #: searching model "news"
undefined method 'id' for #: searching model "documents"
undefined method 'id' for #: searching model "projects"
undefined method 'id' for #: searching model "attachments"
...

**Comment by picman** [comment]
Fixed.
