### ISSUE TITLE
Document Module needs to be enabled

### ISSUE THREAD

**Issue by bennun** [xelkano/redmine_xapian#5]
Hi,
I have to say this is an awesome plugin. I was asked to include full-text searching for Microsoft document attachments. I looked into this plugin, and it was exactly what I needed. I followed your steps, and just ran into a minor glitch. First, I was not getting any hits on my main project. I had the Files module enabled, not Documents. I enabled Documents, and disabled Files, and it worked beautifully. You may need to add that to your readme, assuming it's a requirement. 

Again, nice job, this plugin is a keeper for me.  - Josh

 Note: I'm running Ubuntu 10.04 TLS, MySQL, Redmine 1.1.2

**Comment by picman** [comment]
README updated accordingly.
