### ISSUE TITLE
Next development of the plugin

### ISSUE THREAD

**Issue by picman** [xelkano/redmine_xapian#53]
Dear Xelkano,
First of all thank you very much for such an excellent plugin which has extended Redmine searching abilities a lot. Unfortunately it seems to me that the development of this plugin has been stopped. Because I use this plugin and would like to use the latest releases of Redmine I've modified the plugin in order to be compatible with Redmine version >= 3.
I can fork your code and to continue in development in my own fork but it seems to me better to continue directly here.
Would you consider as valuable to grant me developer status on this project to be able to continue with development and the project maintenance?

**Comment by xelkano** [comment]
Hi!,

I've just added you as a colaborator on the repository, I agree with you that it can be the best option as I have no time now to follow with the development of this plugin.

Thanks very much for your contribution.

**Comment by Krakozaber** [comment]
great

**Comment by picman** [comment]
Thanks!

**Comment by jusplayin** [comment]
Thanks for stepping up to the plate! I was thinking that I should move away from this plugin or just deal with my fork. This is a much better situation.
