### ISSUE TITLE
repository indexing

### ISSUE THREAD

**Issue by Krakozaber** [xelkano/redmine_xapian#56]
when run ./redmine_xapian/extra/xapian_indexer.rb
Mon Jun 22 08:04:03 2015: /redmine/files/xapian_index/repodb
/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:381:in `add_or_update_index': wrong number of arguments (7 for 9) (ArgumentError)
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:304:in `block in walkin'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:297:in `each'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:297:in `walkin'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:324:in `block in indexing_diff'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:322:in `each'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:322:in `indexing_diff'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:180:in `indexing'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:549:in `block (2 levels) in <main>'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:540:in `each'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:540:in `block in <main>'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:534:in `each'
	from /redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:534:in `<main>'

**Comment by picman** [comment]
Fixed. Thank your for the bug report.

**Comment by Krakozaber** [comment]
sory but 
str. 426 and 428 is not true
    FileUtils.cp indexconf.path, '/home/kpicman/from.txt'
    FileUtils.cp itext.path, '/home/kpicman/to.txt'

**Comment by picman** [comment]
Oops! I haven't tested it properly yet.

**Comment by picman** [comment]
Hopefully Okay now.

**Comment by Krakozaber** [comment]
Thanks.
