### ISSUE TITLE
xapian_indexer.rb --resetlog 

### ISSUE THREAD

**Issue by Krakozaber** [xelkano/redmine_xapian#58]
xapian_indexer.rb -r -x
Mon Jun 22 15:34:08 2015: /mnt/data/redmine/files/xapian_index/repodb
/mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:239:in `walk': wrong number of arguments (5 for 6) (ArgumentError)
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:245:in `block in walk'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:242:in `each'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:242:in `walk'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:260:in `block in indexing_all'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:257:in `each'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:257:in `indexing_all'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:177:in `indexing'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:549:in `block (2 levels) in <main>'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:540:in `each'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:540:in `block in <main>'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:534:in `each'
	from /mnt/data/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:534:in `<main>'

**Comment by picman** [comment]
Fixed. Thank you for the bug report.
