### ISSUE TITLE
Redmine plugin registration

### ISSUE THREAD

**Issue by picman** [xelkano/redmine_xapian#61]
Dear Xelkano,
Could you delete Xapian plugin registration on Redmine web: http://www.redmine.org/plugins/redmine_xapian . I will recreate the registration there in order to be able to edit it.
Thank you.

**Comment by picman** [comment]
Any reaction?

**Comment by xelkano** [comment]
Hi picman,

sorry for the late replay, I've removed the plugin page on redmine site.

BR,

**Comment by picman** [comment]
Great! Thank you. I've made a new registration.
http://www.redmine.org/plugins/xapian_search
