### ISSUE TITLE
Error occurs when I run "ruby xapian_indexer.rb -v"

### ISSUE THREAD

**Issue by marilawang** [xelkano/redmine_xapian#62]
```
Mon Sep 14 15:34:01 2015: - Trying to load Redmine environment <</data/redmine-3.1.0/config/environment.rb>>...
Mon Sep 14 15:34:04 2015: - Redmine environment [RAILS_ENV=production] correctly loaded ...
Mon Sep 14 15:34:04 2015: - ERROR! /usr/bin/omindex does not exist, exiting...
```

and I don't know how to install "omindex"...

**Comment by picman** [comment]
Please see the README file:

1.1. Required packages

Redmine >= 3.0

To use xapian search engine you must install libxapian-ruby and xapian-omega packages (on Ubuntu). To index some files with omega you may have to install some other packages like xpdf, antiword, …

**Comment by marilawang** [comment]
I installed xapian-omega and now new error occured:

```
Mon Sep 14 15:45:59 2015: - Trying to load Redmine environment <</data/redmine-3.1.0/config/environment.rb>>...
Mon Sep 14 15:46:03 2015: - Redmine environment [RAILS_ENV=production] correctly loaded ...
Mon Sep 14 15:46:03 2015: - /var/tmp/omindex/english does not exist, creating ...
Mon Sep 14 15:46:03 2015: - Indexing files under /data/redmine-3.1.0/../files with omindex stemming in english ...
xapian_indexer.rb:438:in `system_or_raise': "/usr/local/bin/omindex -s english --db /var/tmp/omindex/english /data/redmine-3.1.0/../files --url / > /dev/null" failed (RuntimeError)
	from xapian_indexer.rb:504:in `block in <main>'
	from xapian_indexer.rb:489:in `each'
	from xapian_indexer.rb:489:in `<main>'

```

**Comment by picman** [comment]
Again, please read the README file and use xapian_indexer.rb instead of omindex eg:

``` ruby
ruby extra/xapian_indexer.rb -v
```

Don't forget to change default values of global variables in xapian_indexer.rb according to your environment first.

**Comment by marilawang** [comment]
I have read README before I ran  "ruby extra/xapian_indexer.rb -v"

code in the file "xapian_indexer.rb":

```
# omindex binary path
$omindex      = '/usr/bin/omindex'
```

cause the error above...

**Comment by picman** [comment]
Please increase your log level in redmine/config/additional_environment.rb:
```ruby
config.logger.level = Logger::DEBUG
```
I see no useful information in your log output now.

**Comment by picman** [comment]
Any progress? Can I close the issue?
