### ISSUE TITLE
404 on /settings/plugin/redmine_xapian 

### ISSUE THREAD

**Issue by jusplayin** [xelkano/redmine_xapian#63]
Testing out Redmine 3.1 with redmine_xapian and I can't seem to get the plugin configuration page to work.. What am I missing?

Administration > Information (everything is checked)
<pre>
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-openbsd]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.9
  Filesystem                     
Redmine plugins:
  redmine_xapian                 1.6.3
</pre>

production.log:
<pre>
Started GET "/settings/plugin/redmine_xapian" for 192.168.1.158 at 2015-11-13 17:59:02 -0500
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_xapian"}
  ^[[1m^[[36m (0.3ms)^[[0m  ^[[1mSELECT MAX(`settings`.`updated_on`) FROM `settings`^[[0m
  ^[[1m^[[35mUser Load (0.3ms)^[[0m  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (6.7ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.5ms)
  ^[[1m^[[36mUserPreference Load (0.3ms)^[[0m  ^[[1mSELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 1 LIMIT 1^[[0m
  ^[[1m^[[35mProject Load (0.3ms)^[[0m  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`p
roject_id` WHERE (projects.status<>9) AND `members`.`user_id` = 1 AND (projects.status<>9) AND `projects`.`status` = 1  ORDER BY projects.name
Completed 404 Not Found in 52ms (Views: 30.0ms | ActiveRecord: 1.3ms)
</pre>

**Comment by jusplayin** [comment]
More information: 
The search page appears to be the default redmine search page as opposed to the Xapian looking page (Not sure if it is supposed to look different in this version).
The database I used was upgraded from 2.5.2. 

Is there anything else I can provide regarding this issue?

**Comment by picman** [comment]
It seems to as the plugin is not correctly installed. The search page should looks like:

![untitled](https://cloud.githubusercontent.com/assets/779003/11366707/473528e6-92af-11e5-8be7-f2ad39b936f3.png)

Have you installed required packages and followed installation steps as written in README file?

I see that you use OpenBSD. It's a little bit exotic system. It might be related.

**Comment by jusplayin** [comment]
I've installed the older plugin successfully many times on redmine 2.X... It didn't seem like the process changed much. I have tried the new version several times already on redmine 3.X with no luck yet..

My search looks the same:
![image](https://cloud.githubusercontent.com/assets/4462440/11378428/13c2a024-92b9-11e5-893a-7506fa1a20d3.png)

Shouldn't there be an Xapian logo when it's working?

I'm going to try to redo the process in a vanilla redmine and see if it works out better. I have been using upgraded databases from 2.X.

**Comment by picman** [comment]
I've removed the logo as I didn't like it ;-) That's not the problem. But, there is obviously something wrong. Your screen-shot displays the standard Redmine search screen. Please note the "Options", which shouldn't be there.

**Comment by jusplayin** [comment]
Well, vanilla redmine seems to behave the same way as with my upgraded databases... So, I don't think that is it.

Also, I guess I could have been leaving out potential important information. To use the redmine_xapian plugin I edit the Gemfile as follows:
<pre>
-gem "xapian-ruby"
+gem "xapian-full-alaveteli", "~> 1.2.9.5"
</pre>
I do this because I have had problems building  'xapian-ruby'. It has worked fine with Redmine 2.X... Not sure that this would really affect anything. 

So, it seems Redmine knows that redmine_xapian is there but doesn't seem to be able to use it for anything (i.e. No plugin conf page. No Xapian search page). Do you have any ideas on where things are breaking down or how I can track down the root issue?

**Comment by picman** [comment]
Right permissions of *plugin/redmine_xapian*?

Redmine simply register all sub-directories(that contains *init.rb* file) under *plugins* directory as plugins. You can investigate the functionality in *libs/redmine/plugin.rb Plugin::load*.

**Comment by picman** [comment]
No feedback for two weeks => closed
