### ISSUE TITLE
Search file contents does not work at all but on console

### ISSUE THREAD

**Issue by novumcoder** [xelkano/redmine_xapian#64]
After installing everything needed for xapian and omega i indexed all files.

Running the quest call with my --db /var/tmp/omindex/english database iam able to find anything from within file contents.

But searching on redmine ticking files i dont get any results. It seems its not using the omindex at all from redmine. What is missing here?

I also see the SearchController is replaced by the redmine_xapian one. But it seems its not using the omindex database at all.

**Comment by picman** [comment]
The database path must be set in the plugin's settings; *Directory containing Xapian databases* option. Have you set that?

**Comment by picman** [comment]
There should be */var/tmp/omindex* in your case; without */english*.

**Comment by novumcoder** [comment]
Tried any possible directory including /var/tmp/omindex. Ticket Documents and Files on search while searching something which gives me results on the linux console with my quest call. Nothing in the redmine logs indicating its using the omindex. I see, its using the plugins search controller, but thats it.

**Comment by picman** [comment]
Set log level to debug in your *additional_envitonment.tb* file. The you should see some output while searching.

```ruby
config.log_level = :debug
```

**Comment by novumcoder** [comment]
I did that already. This is what happens once i hit the search button having Documents and Files ticked.

Started GET "/projects/projectname/search?utf8=%E2%9C%93&q=ListView&scope=&all_words=&all_words=1&titles_only=&titles_only=1&documents=1&attachme                                   nts=1&commit=Submit" for 192.168.1.12 at 2015-12-03 11:42:01 +0100
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"ListView", "scope"=>"", "all_words"=>"1", "titles_only"=>"1", "documents"=>"1", "attachments"=>"1", "commit"=>"Submit",                                    "id"=>"projectname"}
   (0.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 63 LIMIT                                    1
  Current user: johndoe (id=63)
  Project Load (0.2ms)  SELECT  `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'projectname' LIMIT 1
   (0.2ms)  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 157
   (0.2ms)  SELECT DISTINCT `documents`.`created_on`, `documents`.`id` FROM `documents` INNER JOIN `projects` ON `projects`.`id` = `documents`.`project_id                                   ` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='documents')) AND (documents.project_id IN (1                                   57)) AND (((title LIKE '%ListView%')))  ORDER BY `documents`.`created_on` DESC, `documents`.`id` DESC
Attachment::search
   (0.7ms)  SELECT DISTINCT `attachments`.`created_on`, `attachments`.`id` FROM `attachments` JOIN issues ON attachments.container_id = issues.id JOIN pro                                   jects ON issues.project_id = projects.id WHERE (attachments.container_type = 'Issue' AND projects.status = 1 AND projects.status <> 9 AND projects.id IN (                                   SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking') AND projects.id IN (157)) AND (((LOWER(attachments.filename) LIKE '%listview%                                   ')))
   (0.6ms)  SELECT DISTINCT `attachments`.`created_on`, `attachments`.`id` FROM `attachments` JOIN messages ON attachments.container_id = messages.id JOIN                                    boards ON boards.id = messages.board_id JOIN projects ON boards.project_id = projects.id WHERE (attachments.container_type = 'Message' AND projects.statu                                   s = 1 AND projects.id IN (157)) AND (((LOWER(attachments.filename) LIKE '%listview%')))
   (0.6ms)  SELECT DISTINCT `attachments`.`created_on`, `attachments`.`id` FROM `attachments` JOIN wiki_pages ON attachments.container_id = wiki_pages.id                                    JOIN wikis ON wikis.id = wiki_pages.wiki_id JOIN projects ON wikis.project_id = projects.id WHERE (attachments.container_type = 'WikiPage' AND projects.st                                   atus = 1 AND projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='wiki') AND projects.id IN (157)) AND (((                                   LOWER(attachments.filename) LIKE '%listview%')))
   (0.8ms)  SELECT DISTINCT `attachments`.`created_on`, `attachments`.`id` FROM `attachments` JOIN projects ON projects.id = container_id WHERE (container                                   _type = 'Project' AND projects.status = 1 AND projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='files')                                    AND projects.id IN (157)) AND (((LOWER(attachments.filename) LIKE '%listview%')))
  Member Exists (0.2ms)  SELECT  1 AS one FROM `members` INNER JOIN `projects` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 63                                    AND (projects.status<>9) LIMIT 1
  Rendered plugins/redmine_xapian/app/views/search/index.html.erb within layouts/base (7.0ms)
  UserPreference Load (0.2ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 63 LIMIT 1
  Project Load (0.2ms)  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN                                    `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 63 AND (projects.status<>9) AND `projects`.`status` = 1  ORDER BY projec                                   ts.name
  Project Load (0.2ms)  SELECT `projects`.* FROM `projects` WHERE (projects.lft < 264 AND projects.rgt > 265) AND (projects.status <> 9)  ORDER BY `projec                                   ts`.`lft` ASC
Completed 200 OK in 89ms (Views: 54.0ms | ActiveRecord: 6.7ms)

**Comment by picman** [comment]
*titles_only=1* is the problem. Uncheck this option for the full-text search.

**Comment by novumcoder** [comment]
Ok, now in the logs i see the search ongoing against the omindex with results. But still redmine shows me 0 Results.

But the results from the omindex seem to have a problem.

Wrong format of document data :url=/2015/03/150303103727_bugreport.html
sample=update.CRM bug report User Benutzer SU Bearbeiter SU Benutzergruppe 0 Stationsnummer 3 Rechte SR Central NEW Rollen Konfiguration [Messer (#1002)] [BTB_STD_SP_web (#1001)] [UPDATE_DEFAULT Offline (#6)] [UPDATE_DEFAULT (#0)] Telefonprofil Kein Telefonprofil ausgewählt Sprache Deutsch (language ger , sub language 2) Browser User Agent Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; InfoPath.3) ...
caption=update.CRM bug report
type=text/html
modtime=1425375420
size=811991

What does this mean?
"Wrong format of document data :url=/2015/03/150303103727_bugreport.html"

**Comment by picman** [comment]
It means that the data from the database are not in expected format.
Could you try it again with the fix I've just committed?

**Comment by novumcoder** [comment]
Hey, now it works. I'm now getting results on redmine search, matching with those i found on console. Thanks.
