### ISSUE TITLE
inapplicable default search options

### ISSUE THREAD

**Issue by renepavlik** [xelkano/redmine_xapian#65]
There are almost all check boxes off by default in the search dialog after installing this plugin. Except `Wiki pages` and `Project`. Additionally the `Search titles only` is being checked, which also reduces the results.
Basically, typing anything to the search box in the top right corner gives zero results in most cases.
Since I have also the DMSF plugin installed, I have to click and check 9 check boxes and uncheck one (the titles only) to get proper search results. And repeat this on every new search query!

Here is the perfect default how it should look:
http://www.redmine.org/projects/redmine/search
Which reads: find all, limit as needed afterwards

As far as I can tell, the `search_controller_patch.rb` modifies the search page.
For example, the `Search titles only` is hardcoded here:
https://github.com/xelkano/redmine_xapian/blob/master/lib/redmine_xapian/search_controller_patch.rb#L44

Why this file modifies the search controller so hardly? Is it possible to change that to be less strict?

Thanks.

**Comment by picman** [comment]
Okay, switched back to the Redmine standard - full search.
