### ISSUE TITLE
Unable to search attachments using redmine_knowledgebase plugin

### ISSUE THREAD

**Issue by bennun** [xelkano/redmine_xapian#7]
Hello: I've successfully installed redmine_xapian. All my issue, forum and wiki attachments, along with full-text searching, return successful results. However, it does not seem to extend beyond core Redmine. I have installed redmine_knowledgebase plugin, which allows for file attachments in articles. The attachments are placed in the normal ../files directory. Even though I run the index job, it doesn't know grab these attachments. Any ideas?

http://www.redmine.org/plugins/redmine_knowledgebase
https://github.com/alexbevi/redmine_knowledgebase

**Comment by picman** [comment]
It's out of scope of this plugin. Sorry.
