### ISSUE TITLE
Fulltext search options mix up redmine-modules and attachement-location to search

### ISSUE THREAD

**Issue by bashforever** [xelkano/redmine_xapian#72]
First let me shortly explain the setup of our redmine: we are using redmine for project management and not for software development, so the modules Files and Repositories are not used in projects  so they are not activated.
During testing this great plugin, I stumbled across the following design imperative, which IMHO could be improved: the search options for "Files" only shows up if you enable the module "File" on project level. You don't have to have any files stored there, just the module has to be enabled to get the required checkbox. Only then you are able to do a full text search in _the other modules' attachements_ . To allow search of - say- your Ticket-Attachements, nevertheless you have to enable the "Files" module, even if it's not used.

Personally I would expect that the checkbox "All Words" right from the search entry field in combination with "Tickets" should result in a search of the corresponding attachements. This would add the additional functionality to search just attachements of Tickets (not globally). This is what I (as a user) would expect.

Just another point is, that the "Files" checkbox shows up, when there is _more than one project_ selected (or a multi-selection like _my projects_) being made. And this behavior is independent of having the "Files" module activated for any project.

So a workaround for _not_ activating the Files-Modules for all projects would be to instruct the user to select always _more than one_ project, e.g. including the sub project - if available.

Please excuse me for this lengthy description, but I just thought it necessary.

Thanks a lot!

b4e

**Comment by bashforever** [comment]
![image](https://cloud.githubusercontent.com/assets/4045068/17482134/a9231cd8-5d80-11e6-974c-b4d68055f5df.png)

This screenshot shows the behavior: I selected "Dateien" (=Files, only enabled when Files-Module enabled) and all results are attachements from Tickets. So the files-module only serves to control the UI. 
From user perspective I would expect to check "Tickets" and uncheck every other option to receive this result.

**Comment by bashforever** [comment]
Thanks - good idea. Makes the usage much clearer (only point is to check for side effects as I would do this in the locale files). I will check for that.

**Comment by picman** [comment]
_Files/Attachments_ option is always visible now.
