### ISSUE TITLE
Xapian and Easy Redmine

### ISSUE THREAD

**Issue by yoshizava** [xelkano/redmine_xapian#73]
Hi, 

We were in contact by e-mail and as requested I will continue in here. The situation is: I'm trying to index my repositories in EasyRedmine (Linux) and SVN (Windows).
I'm using Windows SVN because it's my old server, I'll change it, but it'll be another step
  
Just for historic information, I attached the last e-mail

I did the test as below: 
easy@symm-db:~/easyredmine/plugins/redmine_xapian/extra$ ruby xapian_indexer.rb -v -r -p 150
Trying to load Redmine environment <</home/easy/easyredmine/config/environment.rb>>...
Redmine environment [RAILS_ENV=production] correctly loaded ...
- Indexing repositories for ELEVADORES ZENIT - 000039...
Fetch changesets: ELEVADORES ZENIT - 000039 - zenit
Latest revision: ELEVADORES ZENIT - 000039 - zenit - 5
/usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query': Mysql2::Error: Table 'easy.indexinglogs' doesn't exist: SHOW FULL FIELDS FROM `indexinglogs` (ActiveRecord::StatementInvalid)
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:312:in `execute_and_free'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:457:in `columns'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/attributes.rb:93:in `columns'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/attributes.rb:98:in `columns_hash'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/relation/query_methods.rb:967:in `each'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/relation/query_methods.rb:967:in `partition'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/relation/query_methods.rb:967:in `create_binds'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/relation/query_methods.rb:954:in `build_where'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/relation/query_methods.rb:584:in `where!'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/relation/query_methods.rb:574:in `where'
        from /usr/local/rvm/gems/ruby-2.2.4-railsexpress/gems/activerecord-4.2.5.2/lib/active_record/querying.rb:10:in `where'
        from xapian_indexer.rb:168:in `indexing'
        from xapian_indexer.rb:517:in `block (2 levels) in <main>'
        from xapian_indexer.rb:515:in `each'
        from xapian_indexer.rb:515:in `block in <main>'
        from xapian_indexer.rb:509:in `each'
        from xapian_indexer.rb:509:in `<main>'

Do you think it's because of the EasyRedmine structure?

Thanks
Wesley Yoshizava

[xapian_email.txt](https://github.com/xelkano/redmine_xapian/files/464211/xapian_email.txt)

**Comment by picman** [comment]
This is the problem:
```
Mysql2::Error: Table 'easy.indexinglogs' doesn't exist
```
Run the migration task:
```
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
```
