### ISSUE TITLE
Search results for tickets truncated?

### ISSUE THREAD

**Issue by bashforever** [xelkano/redmine_xapian#74]
Redmine Release 3.3.0: Search results display truncated (searchdisplaytuncated)

When you do a search for tickets containing a colon ":" in the title, everything before the title will be cut off when displaying the search results. I logged this issue also to www.redmine.org (http://www.redmine.org/issues/23816 ) but the original redmine site www.redmine.org does not show this behavior. Could it be that the xapian-search page (to my understanding overwriting the redmine search) introduces this behavior?

To reproduce:
Do a search for a ticket and every text before the ":" will not show up.

As we are using initial descriptors in our ticket titles this is not a purely cosmetical but rather important problem.

Thanks a lot

IW

**Comment by bashforever** [comment]
Hi!
I did just now a clean install of redmine 3.3.0 and the installed as only plugin Xapian-search. The clean install of redmine does not show the described, but the xapian-search introduces the issue described. 
[20160913_How to reproduce.pdf](https://github.com/xelkano/redmine_xapian/files/469550/20160913_How.to.reproduce.pdf)

**Comment by bashforever** [comment]
Did unintended close issue.

Sorry

Bashforever

**Comment by bashforever** [comment]
Hi Karel,

I investigated on this on my own and (being only an old school C/FORTRAN/bash developer) nevertheless managed to find a possible solution in app/views/index.html.erb:

The following change reverts to the "classical" redmine behavior in showing the search results:

---

 redmine@ubuntu-test:~/redmine/plugins/redmine_xapian/app/views/search$ diff index.html.erb  index.html.erb_xapian
 77c77
 <           <%= link_to(highlight_tokens(e.event_title.truncate(255), @tokens), e.event_url) %>
 - - -
 >           <%= link_to(highlight_tokens(e.event_title.truncate(255).split(': ').last, @tokens), e.event_url) %>

---
Sorry for the wierd formatting - I found no method inserting code proprely in a comment.

I identified the "split(':')"-part to introduce the problem and truncating Issue titles. Do you think it save to change the behavior this way? 

Thanks a lot

Bashforever

**Comment by picman** [comment]
Fixed. "split(':')" was the problem. Thank you.
