### ISSUE TITLE
index all repositories

### ISSUE THREAD

**Issue by coureur** [xelkano/redmine_xapian#76]
hi,

I can't index repositories in non-public projects. Is it normal ? how can i do that ?

Thanks

**Comment by coureur** [comment]
Hi,

Another things, when i want to index files, xapian_indexer doesn't idex subdirectories of redmine/file.

So i updated the xapian_idexer.rb, i added the --depth-limit=0 argument to the omindex command.

**Comment by picman** [comment]
> I can't index repositories in non-public projects. Is it normal ? how can i do that ?

No, it's not. Please add some details from the indexing. What is the output?
