### ISSUE TITLE
Do I need to disable Xapian in DMSF

### ISSUE THREAD

**Issue by man2004** [xelkano/redmine_xapian#77]
I have DMSF installed and enabled Xapian in cron to search DMSF document. If I also install this plugin, do I need to disable the original Xapian in cron and just run this plugin? My purpose is to be able to search attachment and DMSF documents.

**Comment by carlolars** [comment]
I have installed both DMSF and this Xapian. When I installed DMSF I chose to install without Xapian, and then I installed this plugin and after that I configured Xapian for DMSF.
What I found out is that this plugin and DMSF must have different xapian databases, and the cron job must run both the indexer for this plugin and the indexer for DMSF.

**Comment by picman** [comment]
Exactly, searching in DMSF and searching in attachments are two independent processes.
