### ISSUE TITLE
Search scope not displaying properly

### ISSUE THREAD

**Issue by acosonic** [xelkano/redmine_xapian#81]
I have dmsf plugin installed, and it works for users which are internally authorized, however it does not work for users authorized via LDAP.

This is excerp from debug log

 AuthSource Load (0.3ms)  SELECT "auth_sources".* FROM "auth_sources" WHERE "auth_sources"."onthefly_register" = $1  [["onthefly_register", "t"]]
Authenticating 'user@example.com' against 'EXAMPLE DOMAIN'
  AnonymousUser Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('AnonymousUser')  ORDER BY "users"."id" ASC LIMIT 1
Completed in: 33 ms | 401 [https://redmine.example.com/dmsf/webdav/test*project]

**Comment by picman** [comment]
1. This plugin has nothing to do with [DMSF plugin](https://github.com/danmunn/redmine_dmsf).
2. Your log file snippet is related to a WebDAV request?!?

**Comment by acosonic** [comment]
yes, so LDAP users can login normally when they login to Redmine, but when they try to login (map as windows drive) as LDAP users, it does not work.
