### ISSUE TITLE
doesn't work with redmine v3.4.1

### ISSUE THREAD

**Issue by muradurm** [xelkano/redmine_xapian#82]
After upgrading from redmine v3.3.3 to v3.4.1 the plugin doesn't work.

bundle exec rake redmine:plugins:migrate RAILS_ENV="production"

rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown storage engine 'Mroonga': SHOW FULL FIELDS FROM `fts_attachments`
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:120:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:120:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:119:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:119:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in `columns'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:109:in `table'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:97:in `block in tables'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:96:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:96:in `tables'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:38:in `dump'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:22:in `dump'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:240:in `block (4 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:239:in `open'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:239:in `block (3 levels) in <top (required)>'
/opt/redmine/redmine-3.4.1/lib/tasks/redmine.rake:140:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Mysql2::Error: Unknown storage engine 'Mroonga'
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:120:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:120:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:119:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:119:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in `columns'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:109:in `table'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:97:in `block in tables'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:96:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:96:in `tables'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:38:in `dump'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/schema_dumper.rb:22:in `dump'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:240:in `block (4 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:239:in `open'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:239:in `block (3 levels) in <top (required)>'
/opt/redmine/redmine-3.4.1/lib/tasks/redmine.rake:140:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)

**Comment by picman** [comment]
I haven't tested it with Redmine 3.4.1 yet but the error doesn't seem to be related to the plugin.
```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown storage engine 'Mroonga': SHOW FULL FIELDS FROM fts_attachments
```

**Comment by picman** [comment]
Just tested with Redmine 3.4. Your problem is in Mysql2::Error: Unknown storage engine 'Mroonga'.
