### ISSUE TITLE
Error: not a Word Document

### ISSUE THREAD

**Issue by tmc9031** [xelkano/redmine_xapian#83]
Version: 1.6.6
cmd: 

    ruby /home/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb -f -v

output:
```
Indexing "129124445033.doc" as application/msword ... added
```
but the other doc
```
Indexing "130124191044.doc" as application/msword ... /home/redmine/files/130124191044.doc is not a Word Document.
Skipping - "antiword -mUTF-8.txt /home/redmine/files/130124191044.doc" failed
```

What wrong ??? but i use "catdoc" can show 130124191044.doc text
I want to know how redmine_xapian judge doc is a Word Document or not ???

**Comment by picman** [comment]
_xapian_indexer.rb_ uses the command _omindex_. _omindex_ then uses installed tools to convert different document types to plain text. According to the documentation:

> MS Word documents (.dot) if antiword is available (.doc files are left to libmagic, as they may actually be RTF (AbiWord saves RTF when asked to save as .doc, and Microsoft Word quietly loads RTF files with a .doc extension), or plain-text).

_libmagic_ library is used to convert _*.doc_ documents not _catdoc_. See https://xapian.org/docs/omega/overview.html.
