### ISSUE TITLE
Error: Plugin redmine_xapian was not found.

### ISSUE THREAD

**Issue by tmc9031** [xelkano/redmine_xapian#84]
Version: v1.6.7
follow 1.2. Plugin installation

```
bundle exec rake redmine:plugins:migrate RAILS_ENV="production" NAME=redmine_xapian
Plugin redmine_xapian was not found.
```

Then new version can NOT install ???

**Comment by picman** [comment]
1. Do you run the migration from within the Redmine folder, e.g. `/opt/redmine'?
2. Is the plugin installed in the plugin sub-folder, e.g. `/opt/redmine/plugins/redmine_xapian'?

**Comment by hermannpencole** [comment]
Hello,
i have the same issue, with the last version (1.6.7) ;
```bash
# pwd
/usr/src/redmine
# ls /usr/src/redmine/plugins/redmine_xapian/
CHANGELOG  COPYRIGHT.txt  GPL.txt  Gemfile  README.md  app  assets  config  db  extra  init.rb  lib  test
# RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_xapian
Plugin redmine_xapian was not found.
# RAILS_ENV=production bundle exec rake redmine:plugins:migrate
Migrating redhopper (Redhopper plugin)...
Migrating redmine_agile (Redmine Agile plugin (Light version))...
```

**Comment by tiurlumbangaol** [comment]
hi, i have the same problem with the last version (1.6.7) as well.

**Comment by tiurlumbangaol** [comment]
hi, only after i add this line : 
`gem 'xapian-full-alaveteli'`
on Gemfile, then the redmine_xapian plugin detected. but is it the correct gem name? kindly inform.

**Comment by picman** [comment]
No it's not. It shouldn't be there.

It seems that the problem is caused at the beginning of the _init.tb_ file:

```ruby
begin
  require 'xapian'
  $xapian_bindings_available = true
rescue LoadError
  Rails.logger.warn %{No Xapian search engine interface for Ruby installed => Full-text search won't be available.
                      Install a ruby-xapian package or an alternative Xapian binding (https://xapian.org).}
  $xapian_bindings_available = false
else
....
```

Have you installed ruby-xapian and xapian-omega packages as described in the README file first?

**Comment by hermannpencole** [comment]
👍  For me, I did not do it

**Comment by acosonic** [comment]
Same thing here...

Why don't you update readme and tell us what to type exactly?

gem install xy ?

**Comment by acosonic** [comment]
I'm also proceeding with gem install xapian-full-alaveteli, don't know what else to do.

**Comment by picman** [comment]
But that's wrong! `xapian-full-alaveteli` is obsolete and there is no up to date gem replacement. Prior the plugin installation it's necessary to install Xapian packages as described in README. The installation varies depending on OS and you should follow the instruction on https://xapian.org.

> To use the full-text search engine you must install ruby-xapian and xapian-omega packages. In case of using of Bitnami stack or Ruby installed via RVM it might be necessary to install Xapian bindings from sources. See https://xapian.org for details. To index some files with omindex you may have to install some other packages like xpdf, antiword, ...

**Comment by acosonic** [comment]
Ok, I agree, but there is no clean instruction how to install it... 

I am using rvm and my Redmine instances use different rubies across system...

Because I run multi-redmine installations on 1 host.

There is nothing here: https://xapian.org/docs/bindings/ruby/

How to install it...

Should I say gem install xapian and gem install omega?

**Comment by picman** [comment]
https://xapian.org/download

**Comment by picman** [comment]
In my case (Ubuntu/Debian):
```
aptitude install ruby-xapian
aptitude install xapian-omega
```

**Comment by acosonic** [comment]
Hm, but I followed 

sudo apt-get install xapian-omega libxapian-dev xpdf poppler-utils \
    antiword unzip catdoc libwpd-tools libwps-tools gzip unrtf catdvi \
    djview djview3 uuid uuid-dev xz-utils libemail-outlook-message-perl

Then it lacks
ruby-xapian

**Comment by acosonic** [comment]
On the Readme...

**Comment by picman** [comment]
I'll add it.

**Comment by tiurlumbangaol** [comment]
Hi @picman 

yes, please add it. because i spent 2-3 days try installing xapian, both on centos and ubuntu, both are stuck.... because not success installing required library.

if you give step by step, in very specific command, and inform on which linux distro, that would be very very helpful for us.

xapian would be very very useful for us. but we are stuck installing it.

**Comment by picman** [comment]
Done.

**Comment by acosonic** [comment]
> gem 'xapian-full-alaveteli'

This is still problem with Redmine 4.1 and ruby 2.6.3

However, underlying system is Ubuntu 14.04 ...

**Comment by picman** [comment]
Ubuntu 14.04 LTS reaches end of life on April 30, 2019. The gem _xapian-full-alaveteli_ is not used in the plugin for quite a long time and has been replaced with _ruby-xapian_ package. _xapian-omega_ and _ruby-xapian_ must be compatible in versions.
