### ISSUE TITLE
feature: add  "--retry-failed" to omindex in  xapian_indexer.rb

### ISSUE THREAD

**Issue by flece** [xelkano/redmine_xapian#85]
* if you have many files to index the indexing process needs more memory
* if you have not enough memory, tools like "pdftotext" exit with an error

Quote from https://xapian.org/docs/omega/overview.html :

"Starting from version 1.3.4, omindex now tracks failed files in the user metadata of the database, along with their sizes and last modified times, and uses this data to skip files which previously failed and haven't changed since. You can force omindex to retry such files using the --retry-failed option."

live example:  
* 7GB of files to index
* with 4 GB RAM it took 120 minutes to index 7500 files (no problems)
* with 2 GB RAM it took 14 minutes to index 1200 files (many files failed)

i added "--retry-failed" to omindex and now i can run xapian_indexer.rb 4 times in a row without raising memory and ending up with an proper index.

**Comment by picman** [comment]
Okay, but the purpose of the optimization is to not keep unsuccessful indexing of certain files. That option just force the command to try it over and over. From an administrator I'd expect to find the origin of problems, to fix it and to re-index the database.
I'd prefer to add a corresponding note into `README` instead of changing `xapian_indexer.rb`.

**Comment by flece** [comment]
no, that option makes omindex to try the "marked as bad" again. there is no other way to make him "forget" the bad ones except to delete the hole index.

xapian_indexer.rb is a wrapper around omindex. but it lacks many options from omindex. this particular option is the only way to get my index done without raising memory to twice the amount it needs on a daily basis.

I like to see this implemented as an option. options never hurt and its easy to implement. 

`$retryfailed      = 0`
`opts.on('-R', '--retry-failed',            'retry files which omindex failed to extract text') {$retryfailed += 1}`
`cmd << ' --retry-failed' if $retryfailed > 0`

Thank you, flece

**Comment by picman** [comment]
I understand now. I'll add it.

**Comment by picman** [comment]
Done.
