### ISSUE TITLE
pdf and Word(.doc)  files are not seachable

### ISSUE THREAD

**Issue by ananas3** [xelkano/redmine_xapian#88]
Environment)
Redmine version 3.3
Xapian version 1.2.8-1

Issue)
I run "xapian_indexer.rb -v -r" to index repository  which includes pdf(.pdf)  Word(.doc) and Word(.docx)
After this  I could search words of  Word(.docx) files on Redmine. 
I could not search  pdf(.pdf)  and Word(.doc) .
So I checked   "def convert_to_text(fpath, type)" (line 340) in "xapian_indexer.rb".
Word(.docx) type files are converted to text(xml)  by "unzip"   and the converted  text is passed to the Xapian's  '/bin/scriptindex'  command.
On the other hand pdf(.pdf) and Word(.doc) files are not converted to text  and "body =/usr/bin/pdftotext -enc UTF-8 ..."( or  "body=/usr/bin/catdoc" )  is passed to  '/usr/bin/scriptindex' instead of text.

 Is there any possibility that converting pdf(.pdf) ,word(.doc) to text  has failed either inside   '/usr/bin/scriptindex' (= Xapian Omega)" or "Redmine Xapian plugin"?

**Comment by picman** [comment]
Fixed. Thank you for the bug report.

**Comment by picman** [comment]
Just replace " with ` to fix it. See the related commit above.

**Comment by ananas3** [comment]
Thank you so much for the bug fixing.
PDF and Word(.doc) files became searchable in my environment.
