### ISSUE TITLE
Question: How to make  Japanese/Chinese characters searchable?

### ISSUE THREAD

**Issue by ananas3** [xelkano/redmine_xapian#90]
I want to search Japanese/Chinese characters with the redmine_xapian_plugin.

Xapian.org has supported CJK_NGRAM from 1.2.8 and later by setting environment variable XAPIAN_CJK_NGRAM=1.
[xapian.org document](https://xapian.org/docs/sourcedoc/html/classXapian_1_1TermGenerator.html#ac21eb1850b8e1a3ca785f9a4417973d1a0b31ee76f4e202359c590645280c7027)

So I wrote  "ENV['XAPIAN_CJK_NGRAM']=1"  in the following souce file.
However searching  Japanese/Chinese characters doesn't work well. It sometimes suceed and  sometimes fails. 
If you know  where and when to set  the variable "XAPIAN_CJK_NGRAM=1" with the redmine_xapian_plugin, could you give me the information? 

---
file: redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb 
def xapian_search(tokens xxx
 ENV['XAPIAN_CJK_NGRAM']=1 ←Added.

**Comment by picman** [comment]
According to the Xapian's documentation the flag should be added here, I think:

**plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb**

```ruby
73 - query = qp.parse_query(query_string,Xapian::QueryParser::FLAG_WILDCARD)
73 + query = qp.parse_query(query_string, Xapian::QueryParser::FLAG_WILDCARD | Xapian::QueryParser::FLAG_CJK_NGRAM)
```
I've tested it a little with the following file:

[rice.txt](https://github.com/xelkano/redmine_xapian/files/1919784/rice.txt)

If the flag FLAG_CJK_NGRAM is not set, I can search for Chinese and Japanese texts:

![image](https://user-images.githubusercontent.com/779003/38871646-b7e9d33a-4251-11e8-8e44-208f9079461c.png)

But if I set it, only texts written with Latin characters are search-able.

**Comment by picman** [comment]
Ops, I omitted this crucial sentence in the documentation: "The corresponding option needs to have been used at index time."
So, If I re-index files as follows, I can search Asian text with FLAG_CJK_NGRAM set.

```
XAPIAN_CJK_NGRAM=true ruby plugins/redmine_xapian/extra/xapian_indexer.rb -fxv
```

**Comment by picman** [comment]
Can you test it? If you achieve better results with FLAG_CJK_NGRAM, I'll add it as an option.

**Comment by ananas3** [comment]
Thank you so much.
However your modification was the same effect as mine.
I use  Xapian Omega v1.2.8 ( old and out of support) . Because "FLAG_CJK_NGRAM" is not supported , "Xapian::QueryParser::FLAG_CJK_NGRAM" causes a parameter error.
ENV['XAPIAN_CJK_NGRAM']="1"  was OK after all.

-----
I did following
1. plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb
ENV['XAPIAN_CJK_NGRAM']="1"

2. Index time
I  run xapian_indexer.rb in shellscript where I wrote following. 
export XAPIAN_CJK_NGRAM = "1"
ruby plugins/redmine_xapian/extra/xapian_indexer.rb

**Comment by ananas3** [comment]
In the  xapian document,  FLAG_CJK_NGRAM is defined as   
"With this enabled, spans of CJK characters are split into unigrams and bigrams, with the unigrams carrying positional information. Non-CJK characters are split into words as normal."

Now , on Japanese documents  many  CJK characters are  mixed with Non-CJK characters. So Xapian searching sometimes fails with Japanese characters. I guess success rate of seaching CJK on Redmine  is about 70% with the redmine_xapian plugin.
Anyway if you support XAPIAN_CJK_NGRAM  in the redmine_xapian plugin, it brings good result for CJK documents than now for CJK users!!

**Comment by picman** [comment]
Done.
