### ISSUE TITLE
Xapian not indexing repository if project configuration is blank

### ISSUE THREAD

**Issue by tiurlumbangaol** [xelkano/redmine_xapian#91]
Hi,

Xapian not indexing repository if project configuration is blank.

if we put on xapian_indexer.rb like this : 
$projects      = []

redmine xapian behaves like this : 

- it is NOT indexing any of reposity : incorrect behavior
- it indexing all files from all project : correct behavior

If we put project id, only after that it will index related repository project : 
$projects      = ['prj1']

Can you fix, so even if put as "$projects      = []" redmine xapian will index repositories from ALL projects.

This issue still occurs on redmine xapian latest release (v 1.6.8)

**Comment by picman** [comment]
I don't agree. If I set `$projects = []` in _xapian_indexer.rb_ and than call _ruby xapian_indexer.rb -rv_ all active projects with repository module on are indexed.

**Comment by tiurlumbangaol** [comment]
Hi, i'm confused. i'm not asking for a feature request. it is a bug. i had tested it several time, and the behavior consistent. did you test it from your side?

**Comment by picman** [comment]
Yes, and it worked fine. Please post an output from your indexing. Also try to remove an existing index before indexing. It works for me and without more information I won't be able to find out where is a problem.

**Comment by tiurlumbangaol** [comment]
try to remove an existing index before indexing >> i already remove existing index.

this is the command and output : 
`
bitnami@redmine:/opt/bitnami/apps/redmine/htdocs/plugins/redmine_xapian/extra$ ruby xapian_indexer.rb -rv                      Trying to load Redmine environment <</opt/bitnami/apps/redmine/htdocs/config/environment.rb>>...
Redmine environment [RAILS_ENV=production] correctly loaded ...
bitnami@redmine:/opt/bitnami/apps/redmine/htdocs/plugins/redmine_xapian/extra$
`

**Comment by picman** [comment]
Hm, that's strange. Here is my output from the same command:
```
kpicman@plzn020:~/RubymineProjects/redmine/plugins/redmine_xapian/extra$ ruby xapian_indexer.rb -rv
Trying to load Redmine environment <</home/kpicman/RubymineProjects/redmine/config/environment.rb>>...
Redmine environment [RAILS_ENV=production] correctly loaded ...
- Indexing repositories for Fastboot...
Fetch changesets: Fastboot - main
...
```
Try to modify `xapian_indexer.rb` file and add a few more log messages at the end of the file, #Indexing repositories.

Can't it be related to the visible condition on the following line?

```
$projects = Project.visible.active.has_module(:repository).pluck(:identifier) if $projects.blank?
```

I think that only the public projects are processed in that case. Try to remove `visible`:

```
$projects = Project.active.has_module(:repository).pluck(:identifier) if $projects.blank?
```

**Comment by picman** [comment]
If it's the case, I will modify the code accordingly. All projects should be indexed not just public ones.

**Comment by picman** [comment]
No feedback, but anyway, this is a good change. Closing.
