### ISSUE TITLE
error when triggering repository indexing for a particular project

### ISSUE THREAD

**Issue by tiurlumbangaol** [xelkano/redmine_xapian#92]
calling this comnad will cause error : 
sudo ruby /opt/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb -v -r -p 'proj1'

log : 
Trying to load Redmine environment <</opt/redmine/config/environment.rb>>...
Redmine environment [RAILS_ENV=production] correctly loaded ...
- Indexing repositories for Projectone...
Fetch changesets: Projectone - main
Latest revision: Projectone - main - d88104a3399a36ef0b261620901a7a3ef66d0b23
/opt/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:170:in `indexing': uninitialized constant Indexinglog (NameError)
        from /opt/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:520:in `block (2 levels) in <main>'
        from /opt/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:518:in `each'
        from /opt/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:518:in `block in <main>'
        from /opt/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:512:in `each'
        from /opt/redmine/plugins/redmine_xapian/extra/xapian_indexer.rb:512:in `<main>'

**Comment by picman** [comment]
That's strange. _Indexinglog_ is a model defined in the plugin.

1. I wouldn't run the indexer as the root (_sudo_).
2. I'd run the indexer from redmine directory. (`ruby plugins/redmine_xapian/extra/xapian_indexer.rb -v -r -p 'proj1'`)
3. _indexinglogs_ table exists in your database?

**Comment by picman** [comment]
Maybe the community would appreciate any comments how have you solve it.
