### ISSUE TITLE
Microsoft's acquisition of GitHub

### ISSUE THREAD

**Issue by picman** [xelkano/redmine_xapian#93]
After Microsoft's acquisition of GitHub I wonder whether not to migrate Redmine Xapian project to another portal. [GitLab](https://gitlab.com/) or [Bitbucket](https://bitbucket.org/) come to my mind. What Redmine Xapian community thinks about that? Are there any reason why not doing that? Please comment.

**Comment by acosonic** [comment]
It's unlikely that Microsoft will immediately destroy github, although it eventually will...  


![microsoft knocking](https://user-images.githubusercontent.com/862015/41088449-decd7856-6a3f-11e8-9f19-80a08bcd0e29.jpg)


So I guess you do have enough time to take it slow and migrate it, I am sure there are going to be
new and completely open-source alternatives...

For example I am considering offering some of my servers, but I don't have time to do it :(
