### ISSUE TITLE
Exception throw when I run ruby xapian_indexer.rb -v -f 

### ISSUE THREAD

**Issue by yaocanwei** [xelkano/redmine_xapian#95]
![image](https://user-images.githubusercontent.com/4312268/52555449-bf053280-2e24-11e9-9ef2-8eeb4370d50e.png)

**Comment by picman** [comment]
Please post how and where you run the script.

**Comment by yaocanwei** [comment]
ok.Thank you for replying. The screenshot below show how and where I run the script.
![image](https://user-images.githubusercontent.com/4312268/52577561-55554a80-2e5d-11e9-900e-ac5f7403c60a.png)

**Comment by yaocanwei** [comment]
When I comment the line and run the script.
`ruby redmine_xapian/extra/xapian_indexer.rb -v`
It throw argument exception.
```
Trying to load Redmine environment <</redmine/config/environment.rb>>...
~/.rvm/gems/ruby-2.3.0@rails4.2/gems/yard-0.9.14/lib/yard/globals.rb:20:in `log': wrong number of arguments (given 1, expected 0) (ArgumentError)
from redmine_xapian/extra/xapian_indexer.rb:468:in `<main>'
```

**Comment by yaocanwei** [comment]
ahh^_^. Why commented this line? It was used in below code.

![image](https://user-images.githubusercontent.com/4312268/52579569-6011de80-2e61-11e9-890a-b067b7857d42.png)

**Comment by picman** [comment]
Hm, that's strange. ```log``` function is defined in the file and has got even two parameters:
```ruby
def log(text, error = false)  
  if error
    $stderr.puts text
  elsif $verbose > 0    
    $stdout.puts text
  end  
end
```
What do you exactly have at line 468?

**Comment by yaocanwei** [comment]
The line 468:
![image](https://user-images.githubusercontent.com/4312268/52604817-63c85400-2ea7-11e9-84fa-89b6e2791060.png)

```
def log(text, error = false)  
  if error
    $stderr.puts text
  elsif $verbose > 0    
    $stdout.puts text
  end  
end
```

**Comment by yaocanwei** [comment]
My redmine version is 3.4. Was it supported?

**Comment by yaocanwei** [comment]
Hello. I fix it by rename log method.

**Comment by picman** [comment]
Yes, it is. It's in a confilct with a global log function defined in YARD gem:

```ruby
# The global {YARD::Logger} instance
#
# @return [YARD::Logger] the global {YARD::Logger} instance
# @see YARD::Logger
def log
  YARD::Logger.instance
end
```

Simply rename all ocurences of log function including its definition to e.g. my_log.

**Comment by picman** [comment]
BTW, you can index your files directly using ```omindex```. It's not necessary to use this script.

**Comment by yaocanwei** [comment]
Thank you. I resolve it by renaming the log method and have a PR .

**Comment by picman** [comment]
Great!
