### ISSUE TITLE
IOError: DatabaseOpeningError: Couldn't detect type of database

### ISSUE THREAD

**Issue by yaocanwei** [xelkano/redmine_xapian#96]
after running script `ruby xapian_indexer.rb -v`full-text search works well. 
When upload new file and run script `ruby xapian_indexer.rb -v` again.
full-text search did not work. It throw exception 
```
databasepath: /home/bdauc/workspace/redmine/file_index/repodb
Can't open Xapian database  - #<IOError: DatabaseOpeningError: Couldn't detect type of database>
Call xapian search service for  "Repofile" completed
```

**Comment by picman** [comment]
Add parameter ```f``` if you don't intend to index repositories: ```ruby xapian_indexer.rb -vf```

**Comment by yaocanwei** [comment]
It still haven't work. When I run `ruby xapian_indexer.rb -vf`

**Comment by picman** [comment]
1. Remove the database.
2. Run ```ruby xapian_indexer.rb -vf```
3. Add a file
4. Run ```ruby xapian_indexer.rb -vf``` again

**Comment by yaocanwei** [comment]
Sorry! You mean remove the file_index folder?

**Comment by picman** [comment]
Yes.

**Comment by yaocanwei** [comment]
I have remove the file_index folder and run the script  again.
It still haven't work.

**Comment by picman** [comment]
If you use ```-f``` option thare can't be ```databasepath: /home/bdauc/workspace/redmine/file_index/repodb``` in the oputput.

**Comment by yaocanwei** [comment]
Hm^_^, I don't know why it can't display for us. 
![image](https://user-images.githubusercontent.com/4312268/52624807-8c257200-2eea-11e9-8bee-931ba239b5e3.png)
But it matches records in the log.
![image](https://user-images.githubusercontent.com/4312268/52624754-67c99580-2eea-11e9-8e4f-4f64e25434eb.png)

**Comment by picman** [comment]
Have you got permission to see those files? I mean the user logged in Redmine.

**Comment by yaocanwei** [comment]
Yes. I logged redmine as admin. But display nothing.

**Comment by yaocanwei** [comment]
I don't know why it worked well before. But When I run the script again, It hasn't worked now.

**Comment by yaocanwei** [comment]
I have resolved it. Thank you very much. The reason why it hasn't displayed for me was I upload the file through dmsf plugin. But I indexing files using redmine_xapian plugin. So It should change the dmsf configuration where redmine_xapian can index.

**Comment by picman** [comment]
Yes, there must be two separated indexes one for Files and another for DMS documents.
