### ISSUE TITLE
Skipping - unknown MIME type

### ISSUE THREAD

**Issue by muradurm** [xelkano/redmine_xapian#99]
Redmine v3.4.9, redmine_xapian v1.6.9

When I run xapian_indexer.rb I can see "Skipping - unknown MIME type" for almost all types of files:
Indexing "xxx.zip" as application/zip ... Skipping - unknown MIME type 'application/zip'
Indexing "xxx.jpg" as image/jpeg ... Skipping - unknown MIME type 'image/jpeg'
Indexing "xxx.TXT" as application/octet-stream ... Skipping - unknown MIME type 'application/octet-stream'
Indexing "xxx.7z" as application/x-7z-compressed ... Skipping - unknown MIME type 'application/x-7z-compressed'

Only few file types are ok:
Indexing "xxx.doc" as application/msword ... added
Indexing "xxx.pdf" as application/pdf ... no text extracted from document body, but indexing metadata anyway
Indexing "xxx.xls" as application/vnd.ms-excel ... added
Indexing "xxx.docx" as application/vnd.openxmlformats-officedocument.wordprocessingml.document ... added
Indexing "xxx.txt" as text/plain ... added

Please suggest how to fix it.

**Comment by picman** [comment]
And how you would like to do a full-text search in JPEG file? Text files only are subject of indexing. In case of _TXT_, try to rename it to _txt_.
